# Generated by Django 3.1 on 2023-07-22 07:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(max_length=200, null=True)),
                ('event_users', models.TextField(null=True)),
                ('description', models.TextField(null=True)),
                ('choices', models.JSONField(null=True)),
                ('event_start', models.DateField(null=True)),
                ('event_end', models.DateField(max_length=50, null=True)),
                ('is_closed', models.BooleanField(default=False, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_admin_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Event Master',
                'verbose_name_plural': 'Event Master',
            },
        ),
        migrations.CreateModel(
            name='EventChoiceMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_choice_name', models.TextField(null=True)),
                ('event_choice_id', models.IntegerField(null=True)),
                ('votes', models.IntegerField(null=True)),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventchoice', to='employeradmin.eventmaster')),
            ],
            options={
                'verbose_name': 'Event Choice Map',
                'verbose_name_plural': 'Event Choice Map',
            },
        ),
    ]
