# Generated by Django 3.1 on 2023-07-22 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeradmin', '0002_auto_20230722_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmaster',
            name='event_status',
            field=models.CharField(default='in progress', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='eventmaster',
            name='total_users',
            field=models.IntegerField(null=True),
        ),
    ]
