# Generated by Django 3.1 on 2023-07-22 08:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employeradmin', '0003_auto_20230722_1410'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventUserMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventuser', to='employeradmin.eventmaster')),
                ('event_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_user_mapping', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Event User Map',
                'verbose_name_plural': 'Event User Map',
            },
        ),
    ]
