# Generated by Django 3.1 on 2023-07-22 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeradmin', '0004_eventusermapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmaster',
            name='is_delete',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
